/*
 * This file is part of ZabbixAgent.NET
 * 
 * ZabbixAgent.NET is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * ZabbixAgent.NET is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ZabbixAgent.NET; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * 
 * Copyright TMCare a/s
 *
 * Used Trademarks are owned by their respective owners, There in ZABBIX SIA and Zabbix.
 */

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;
using ZabbixAgent;

/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="UpdateSoapBinding", Namespace="http://mon.tmcare.dk")]
public class UpdateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public UpdateService() {
			Configuration c = Configuration.getInstance;
			this.Url = c.GetConfigurationByString("UpdateServiceLink");
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://mon.tmcare.dk", ResponseNamespace="http://mon.tmcare.dk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getNewVersionLinkReturn")]
    public string getNewVersionLink(string Customer, string ServerName, string CurrentVersion) {
        object[] results = this.Invoke("getNewVersionLink", new object[] {
                    Customer,
                    ServerName,
                    CurrentVersion});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetNewVersionLink(string Customer, string ServerName, string CurrentVersion, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getNewVersionLink", new object[] {
                    Customer,
                    ServerName,
                    CurrentVersion}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetNewVersionLink(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}
